In [3]:
import cv2
import numpy as np
from keras.models import Sequential, load_model
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense
import os
from keras.preprocessing.image import ImageDataGenerator

In [4]:
NUM_CLASSES = 2

In [28]:
cap = cv2.VideoCapture(0) 
cap.set(3, 640)
cap.set(4, 480) 
cap.set(10, 100) 

folder_name = 'thumbs-up'

folder_path = f'input/myImages3/{folder_name}/'

if os.listdir(folder_path):
    maxnum = max([int(file.split('frame')[1].split('.jpg')[0]) for file in os.listdir(folder_path)])
    i = maxnum
else:
    i = 0

while True: 
    i += 1

    success, img = cap.read()

    cv2.imwrite(folder_path+f'myImages3_{folder_name}_frame{i}.jpg', img)

    cv2.imshow('python', img)   
    
    if cv2.waitKey(20) == 27:  
        break

cv2.destroyWindow("python")  
cap.release()  
cv2.waitKey(1)


-1

In [24]:
input_shape = (28, 28, 1) 


model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, kernel_size=(3, 3), activation='relu')) 
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(128, activation='relu')) 
model.add(Dense(NUM_CLASSES, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])



train_generator = train_datagen.flow_from_directory(
    'input/allImages',
    target_size=(28, 28),
    batch_size=128,
    shuffle=True,
    color_mode='grayscale', 
    class_mode='categorical')

validation_generator = train_datagen.flow_from_directory(
    'input/valImages',
    target_size=(28, 28),
    batch_size=128,
    shuffle=True,
    color_mode='grayscale', 
    class_mode='categorical')  

model.fit(
    train_generator,
    epochs=2,  
    steps_per_epoch=len(train_generator),
    verbose=1,
    validation_data=validation_generator)

model.save('trained_gesture_model28.h5')

Found 11505 images belonging to 2 classes.
Found 2875 images belonging to 2 classes.
Epoch 1/2
90/90 [==============================] - 44s 472ms/step - loss: 0.6226 - accuracy: 0.6389 - val_loss: 0.4971 - val_accuracy: 0.7520
Epoch 2/2
90/90 [==============================] - 36s 404ms/step - loss: 0.3668 - accuracy: 0.8314 - val_loss: 0.2375 - val_accuracy: 0.9106


C:\Users\fluke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [25]:
model = load_model('trained_gesture_model28.h5')

from sklearn.metrics import accuracy_score, classification_report


predictions = model.predict(validation_generator)

accuracy = accuracy_score(validation_generator.labels, np.argmax(predictions, axis=1))
print(f'Accuracy: {accuracy}')

print(classification_report(validation_generator.labels, np.argmax(predictions, axis=1)))

23/23 [==============================] - 7s 301ms/step
Accuracy: 0.5175652173913043
              precision    recall  f1-score   support

           0       0.51      0.55      0.53      1431
           1       0.52      0.49      0.50      1444

    accuracy                           0.52      2875
   macro avg       0.52      0.52      0.52      2875
weighted avg       0.52      0.52      0.52      2875



In [3]:
model = load_model('trained_gesture_model27.h5')

cap = cv2.VideoCapture(0) 
cap.set(3, 640) 
cap.set(4, 480)
cap.set(10, 100)


text = ['hi', 'thumbs-up']
positions = [(50, 50), (50, 100), (50, 150)] 
font = cv2.FONT_HERSHEY_SIMPLEX
font_scale = 1
thickness = 3

image_width, image_height = 28, 28

font_color_red = (0, 0, 255) 
font_color_blue = (255, 0, 0) 


while True: 
    success, img = cap.read()

    resized_img = cv2.resize(img, (image_width, image_height)) 
    grey_img = cv2.cvtColor(resized_img, cv2.COLOR_BGR2GRAY) / 255

    pred = model.predict(np.array([grey_img] ))

    print(pred)

    num = int(np.argmax(pred))

    for i in range(NUM_CLASSES):
        if round(float(pred[:,i]), 3) > 0.5:
            cv2.putText(img, text[i]+f' {round(float(pred[:,i]), 3)}', positions[i], font, font_scale, font_color_red, thickness)
        else:
            cv2.putText(img, text[i]+f' {round(float(pred[:,i]), 3)}', positions[i], font, font_scale, font_color_blue, thickness)
    
    cv2.imshow('python', img) 
    
    if cv2.waitKey(20) == 27: 
        break

cv2.destroyWindow("python")  
cap.release()  
cv2.waitKey(1)




1/1 [==============================] - 0s 228ms/step
[[0.03735711 0.9626429 ]]
1/1 [==============================] - 0s 27ms/step
[[0.07704087 0.9229592 ]]
1/1 [==============================] - 0s 24ms/step
[[0.07887472 0.9211253 ]]
1/1 [==============================] - 0s 24ms/step
[[0.0642634 0.9357366]]
1/1 [==============================] - 0s 24ms/step
[[0.05523469 0.9447653 ]]
1/1 [==============================] - 0s 24ms/step
[[0.04779899 0.952201  ]]
1/1 [==============================] - 0s 25ms/step
[[0.05433433 0.9456657 ]]
1/1 [==============================] - 0s 24ms/step
[[0.05506297 0.94493705]]
1/1 [==============================] - 0s 25ms/step
[[0.04604445 0.95395553]]
1/1 [==============================] - 0s 24ms/step
[[0.04604445 0.95395553]]
1/1 [==============================] - 0s 25ms/step
[[0.05414494 0.9458551 ]]
1/1 [==============================] - 0s 23ms/step
[[0.04752443 0.9524755 ]]
1/1 [==============================] - 0s 27ms/step
[[0.0486105

-1

In [33]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

input_shape = (64, 64, 1)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3), activation='relu', input_shape=input_shape))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(64, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(128, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(256, kernel_size=(3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())
model.add(Dense(512, activation='relu'))
model.add(Dense(256, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(NUM_CLASSES, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

train_generator = train_datagen.flow_from_directory(
    'input/allImages',
    target_size=(64, 64),
    batch_size=128,
    shuffle=True,
    color_mode='grayscale', 
    class_mode='categorical')

validation_generator = train_datagen.flow_from_directory(
    'input/valImages',
    target_size=(64, 64),
    shuffle=True,
    color_mode='grayscale', 
    class_mode='categorical')  

model.fit(
    train_generator,
    epochs=2,  
    steps_per_epoch=len(train_generator),
    verbose=1,
    validation_data=validation_generator)

model.save('trained_gesture_model__2.h5')

Found 11505 images belonging to 2 classes.
Epoch 1/2
90/90 [==============================] - 41s 434ms/step - loss: 0.5127 - accuracy: 0.7178
Epoch 2/2
90/90 [==============================] - 39s 431ms/step - loss: 0.1594 - accuracy: 0.9365


C:\Users\fluke\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [34]:
from sklearn.metrics import accuracy_score, classification_report

validation_generator = train_datagen.flow_from_directory(
    'input/valImages',
    target_size=(64, 64),
    shuffle=True,
    color_mode='grayscale', 
    class_mode='categorical')  



validation_loss, validation_accuracy = model.evaluate(validation_generator)


print(classification_report(validation_generator.labels, np.argmax(predictions, axis=1)))

Found 2875 images belonging to 2 classes.
90/90 [==============================] - 9s 91ms/step - loss: 0.0789 - accuracy: 0.9722
Accuracy: 0.49321739130434783
              precision    recall  f1-score   support

           0       0.49      0.49      0.49      1431
           1       0.50      0.50      0.50      1444

    accuracy                           0.49      2875
   macro avg       0.49      0.49      0.49      2875
weighted avg       0.49      0.49      0.49      2875



In [35]:
validation_generator

In [36]:
from sklearn.metrics import classification_report

# Предполагается, что validation_generator.labels содержит правильные метки
validation_loss, validation_accuracy = model.evaluate(validation_generator)
print(f'Validation Loss: {validation_loss}, Validation Accuracy: {validation_accuracy}')

# Используйте model.predict для получения предсказанных меток
predictions = model.predict(validation_generator)
predicted_labels = np.argmax(predictions, axis=1)

# Сравните предсказанные метки с правильными метками
print(classification_report(validation_generator.labels, predicted_labels))


90/90 [==============================] - 8s 90ms/step - loss: 0.0851 - accuracy: 0.9694
Validation Loss: 0.08510252088308334, Validation Accuracy: 0.9693912863731384
90/90 [==============================] - 8s 90ms/step
              precision    recall  f1-score   support

           0       0.51      0.48      0.50      1431
           1       0.51      0.54      0.53      1444

    accuracy                           0.51      2875
   macro avg       0.51      0.51      0.51      2875
weighted avg       0.51      0.51      0.51      2875

